### ISSUE TITLE
program too big by 116 bytes

### ISSUE THREAD

**Issue by jasperp92** [MKleinSB/pxt-MAX7219_8x8#2]
Es wird diese Fehlermeldung beim verwenden der Blöcke ausgegeben. Wahrscheinlich ist das font_matrix-Array zu lang, und das Programm zu groß, um es in den Preozessorspeicher des minis zu laden:

![image](https://github.com/MKleinSB/pxt-MAX7219_8x8/assets/72135430/6f829cb1-8a5f-41c5-9cf0-2366333ef7d2)

**Comment by MKleinSB** [comment]
Ja, leider. Man muss V3 verwenden oder Bluetooth komplett per Hand entfernen wie bei der Whappsto-Erweiterung. Soll ich das mal machen?

**Comment by jasperp92** [comment]
Ich habe es mal in Makecode V3 verucht und da hat es funktioniert. Ja, wenn du Bluetooth in der pxt.json so wie in der Wappstoerweiterung deaktivieren könntest, wäre das super. Dann könnte man es ggf. auch wieder in der aktuellen Makecodeversion verwenden. Lieben Dank, Jasper

**Comment by MKleinSB** [comment]
Leider reicht der Speicher dann immer noch nicht aus obwohl ich alles rausgeworfen habe was geht :-(

**Comment by MKleinSB** [comment]
Wenn Du MAX7219.ts in custom.ts kopierst und die Erweiterung löschst läuft es!

**Comment by jasperp92** [comment]
Ja, so geht es auch. Jetzt hat es bei mir nicht mehr in der V3 funktioniert. Der lädt sich da irgendwie am Paket kaputt, aber dafür hat es dann in der beta bei mir geklappt zu kompilieren ;)

**Comment by MKleinSB** [comment]
Versuche es jetzt mal mit dem aktuellen makecode!
